services:
  postgres:
    image: postgres:15-alpine3.19
    env_file:
      - ".env"
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_network

networks:
  airflow_network:
    external: false

volumes:
  postgres_data: